# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Fri Jan 27 10:27:35 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1114, 879)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_8 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_3.setMinimumSize(QtCore.QSize(330, 435))
        self.groupBox_3.setMaximumSize(QtCore.QSize(330, 435))
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_7 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.groupBox_5 = QtGui.QGroupBox(self.groupBox_3)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.comboBox_Coloring = QtGui.QComboBox(self.groupBox_5)
        self.comboBox_Coloring.setToolTip("")
        self.comboBox_Coloring.setObjectName("comboBox_Coloring")
        self.gridLayout_4.addWidget(self.comboBox_Coloring, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox_5, 0, 0, 1, 1)
        self.calendarWidget = QtGui.QCalendarWidget(self.groupBox_3)
        self.calendarWidget.setMinimumSize(QtCore.QSize(300, 240))
        self.calendarWidget.setMaximumSize(QtCore.QSize(300, 240))
        self.calendarWidget.setObjectName("calendarWidget")
        self.gridLayout_7.addWidget(self.calendarWidget, 1, 0, 1, 1)
        self.groupBox_6 = QtGui.QGroupBox(self.groupBox_3)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox_6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.pushButton_FirstEntry = QtGui.QPushButton(self.groupBox_6)
        self.pushButton_FirstEntry.setToolTip("")
        self.pushButton_FirstEntry.setObjectName("pushButton_FirstEntry")
        self.gridLayout_6.addWidget(self.pushButton_FirstEntry, 0, 0, 1, 1)
        self.pushButton_Today = QtGui.QPushButton(self.groupBox_6)
        self.pushButton_Today.setToolTip("")
        self.pushButton_Today.setObjectName("pushButton_Today")
        self.gridLayout_6.addWidget(self.pushButton_Today, 0, 2, 1, 1)
        self.pushButton_LastEntry = QtGui.QPushButton(self.groupBox_6)
        self.pushButton_LastEntry.setToolTip("")
        self.pushButton_LastEntry.setObjectName("pushButton_LastEntry")
        self.gridLayout_6.addWidget(self.pushButton_LastEntry, 0, 1, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox_6, 2, 0, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox_3, 1, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setMinimumSize(QtCore.QSize(330, 102))
        self.groupBox_2.setMaximumSize(QtCore.QSize(330, 102))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_CommitStringSearch = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_CommitStringSearch.setToolTip("")
        self.pushButton_CommitStringSearch.setObjectName("pushButton_CommitStringSearch")
        self.gridLayout_2.addWidget(self.pushButton_CommitStringSearch, 0, 2, 1, 1)
        self.pushButton_PreviousSearch = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_PreviousSearch.setEnabled(True)
        self.pushButton_PreviousSearch.setToolTip("")
        self.pushButton_PreviousSearch.setObjectName("pushButton_PreviousSearch")
        self.gridLayout_2.addWidget(self.pushButton_PreviousSearch, 2, 0, 1, 1)
        self.pushButton_NextSearch = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_NextSearch.setToolTip("")
        self.pushButton_NextSearch.setObjectName("pushButton_NextSearch")
        self.gridLayout_2.addWidget(self.pushButton_NextSearch, 2, 1, 1, 1)
        self.pushButton_ResetStringSearch = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_ResetStringSearch.setToolTip("")
        self.pushButton_ResetStringSearch.setObjectName("pushButton_ResetStringSearch")
        self.gridLayout_2.addWidget(self.pushButton_ResetStringSearch, 2, 2, 1, 1)
        self.lineEdit_StringSearch = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_StringSearch.setToolTip("")
        self.lineEdit_StringSearch.setObjectName("lineEdit_StringSearch")
        self.gridLayout_2.addWidget(self.lineEdit_StringSearch, 0, 0, 1, 2)
        self.gridLayout_8.addWidget(self.groupBox_2, 2, 0, 1, 1)
        self.groupBox_4 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.comboBox_ActiveSite = QtGui.QComboBox(self.groupBox_4)
        self.comboBox_ActiveSite.setMinimumSize(QtCore.QSize(180, 26))
        self.comboBox_ActiveSite.setMaximumSize(QtCore.QSize(180, 26))
        self.comboBox_ActiveSite.setToolTip("")
        self.comboBox_ActiveSite.setObjectName("comboBox_ActiveSite")
        self.gridLayout_5.addWidget(self.comboBox_ActiveSite, 0, 0, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox_4, 0, 0, 1, 2)
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setMinimumSize(QtCore.QSize(330, 115))
        self.groupBox.setMaximumSize(QtCore.QSize(330, 115))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.checkBox_Transmitter = QtGui.QCheckBox(self.groupBox)
        self.checkBox_Transmitter.setObjectName("checkBox_Transmitter")
        self.gridLayout_3.addWidget(self.checkBox_Transmitter, 1, 0, 1, 1)
        self.checkBox_AntennaDrive = QtGui.QCheckBox(self.groupBox)
        self.checkBox_AntennaDrive.setObjectName("checkBox_AntennaDrive")
        self.gridLayout_3.addWidget(self.checkBox_AntennaDrive, 0, 0, 1, 1)
        self.checkBox_HeaterControl = QtGui.QCheckBox(self.groupBox)
        self.checkBox_HeaterControl.setObjectName("checkBox_HeaterControl")
        self.gridLayout_3.addWidget(self.checkBox_HeaterControl, 3, 0, 1, 1)
        self.checkBox_Temperature = QtGui.QCheckBox(self.groupBox)
        self.checkBox_Temperature.setObjectName("checkBox_Temperature")
        self.gridLayout_3.addWidget(self.checkBox_Temperature, 2, 0, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox, 3, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(17, 139, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem, 4, 0, 1, 1)
        self.tabWidget_TextFields = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget_TextFields.setObjectName("tabWidget_TextFields")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout = QtGui.QGridLayout(self.tab)
        self.gridLayout.setObjectName("gridLayout")
        self.textBrowser_HistoryLog = QtGui.QTextBrowser(self.tab)
        self.textBrowser_HistoryLog.setObjectName("textBrowser_HistoryLog")
        self.gridLayout.addWidget(self.textBrowser_HistoryLog, 0, 0, 1, 1)
        self.tabWidget_TextFields.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_10 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.plainTextEdit_Comment = QtGui.QPlainTextEdit(self.tab_2)
        self.plainTextEdit_Comment.setObjectName("plainTextEdit_Comment")
        self.gridLayout_10.addWidget(self.plainTextEdit_Comment, 0, 0, 1, 1)
        self.groupBox_7 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_9 = QtGui.QGridLayout(self.groupBox_7)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.pushButton_DeleteComment = QtGui.QPushButton(self.groupBox_7)
        self.pushButton_DeleteComment.setObjectName("pushButton_DeleteComment")
        self.gridLayout_9.addWidget(self.pushButton_DeleteComment, 0, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(18, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem1, 0, 1, 1, 1)
        self.pushButton_PreviousComment = QtGui.QPushButton(self.groupBox_7)
        self.pushButton_PreviousComment.setObjectName("pushButton_PreviousComment")
        self.gridLayout_9.addWidget(self.pushButton_PreviousComment, 0, 2, 1, 1)
        self.pushButton_NextComment = QtGui.QPushButton(self.groupBox_7)
        self.pushButton_NextComment.setObjectName("pushButton_NextComment")
        self.gridLayout_9.addWidget(self.pushButton_NextComment, 0, 3, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(65, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem2, 0, 4, 1, 1)
        self.pushButton_SaveComment = QtGui.QPushButton(self.groupBox_7)
        self.pushButton_SaveComment.setObjectName("pushButton_SaveComment")
        self.gridLayout_9.addWidget(self.pushButton_SaveComment, 0, 5, 1, 1)
        self.gridLayout_10.addWidget(self.groupBox_7, 1, 0, 1, 1)
        self.tabWidget_TextFields.addTab(self.tab_2, "")
        self.gridLayout_8.addWidget(self.tabWidget_TextFields, 1, 1, 4, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1114, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget_TextFields.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "GCA Analysis Tool", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("MainWindow", "Calendar", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("MainWindow", "Coloring Scheme", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_Coloring.setStatusTip(QtGui.QApplication.translate("MainWindow", "Choose different coloring rules for the calendar", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("MainWindow", "Quick Navigation", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_FirstEntry.setStatusTip(QtGui.QApplication.translate("MainWindow", "Focus calendar on the  first recorded date in the history log (excluding ignored dates)", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_FirstEntry.setText(QtGui.QApplication.translate("MainWindow", "First Date", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_Today.setStatusTip(QtGui.QApplication.translate("MainWindow", "Focus calendar on the active date", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_Today.setText(QtGui.QApplication.translate("MainWindow", "Active Date", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_LastEntry.setStatusTip(QtGui.QApplication.translate("MainWindow", "Focus calendar on the last recorded date in the history log (excluding ignored dates)", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_LastEntry.setText(QtGui.QApplication.translate("MainWindow", "Last Date", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "String Search", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_CommitStringSearch.setStatusTip(QtGui.QApplication.translate("MainWindow", "Commit search", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_CommitStringSearch.setText(QtGui.QApplication.translate("MainWindow", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_PreviousSearch.setStatusTip(QtGui.QApplication.translate("MainWindow", "Focus calendar on the previous date in which history log contains search string", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_PreviousSearch.setText(QtGui.QApplication.translate("MainWindow", "Previous", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_NextSearch.setStatusTip(QtGui.QApplication.translate("MainWindow", "Focus calendar on the next date in which history log contains search string", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_NextSearch.setText(QtGui.QApplication.translate("MainWindow", "Next", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_ResetStringSearch.setStatusTip(QtGui.QApplication.translate("MainWindow", "Clear search string", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_ResetStringSearch.setText(QtGui.QApplication.translate("MainWindow", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_StringSearch.setStatusTip(QtGui.QApplication.translate("MainWindow", "Enter search string", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("MainWindow", "Active Site", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_ActiveSite.setStatusTip(QtGui.QApplication.translate("MainWindow", "Choose active site", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "History Log Suppression", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_Transmitter.setText(QtGui.QApplication.translate("MainWindow", "(0d) Transmitter On/Off", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_AntennaDrive.setText(QtGui.QApplication.translate("MainWindow", "(0c) Antenna Drive On/Off", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_HeaterControl.setText(QtGui.QApplication.translate("MainWindow", "(24) Heater Control", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_Temperature.setText(QtGui.QApplication.translate("MainWindow", "(23) Temperature", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_TextFields.setTabText(self.tabWidget_TextFields.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "History Log", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_7.setTitle(QtGui.QApplication.translate("MainWindow", "Comment", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_DeleteComment.setStatusTip(QtGui.QApplication.translate("MainWindow", "Delete this comment from database", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_DeleteComment.setText(QtGui.QApplication.translate("MainWindow", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_PreviousComment.setStatusTip(QtGui.QApplication.translate("MainWindow", "Jump to previous comment", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_PreviousComment.setText(QtGui.QApplication.translate("MainWindow", "Previous", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_NextComment.setStatusTip(QtGui.QApplication.translate("MainWindow", "Jump to next comment", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_NextComment.setText(QtGui.QApplication.translate("MainWindow", "Next", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_SaveComment.setStatusTip(QtGui.QApplication.translate("MainWindow", "Save this comment to database", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_SaveComment.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_TextFields.setTabText(self.tabWidget_TextFields.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Comment", None, QtGui.QApplication.UnicodeUTF8))

